In [1]:
# Importação das bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC
from sklearn.ensemble import ExtraTreesClassifier

In [2]:
# Carregamento da base de dados e criação dos predictors (variáveis independentes - X) e da vclass (variável dependente - y)
credit = pd.read_csv('Credit.csv')
credit

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [3]:
predictors = credit.iloc[:,0:20].values
vclass = credit.iloc[:,20].values

In [4]:
# Transformação dos atributos categóricos em atributos numéricos, passando o índice de cada atributo categórico
labelencoder = LabelEncoder()
predictors[:,0] = labelencoder.fit_transform(predictors[:,0])
predictors[:,2] = labelencoder.fit_transform(predictors[:,2])
predictors[:, 3] = labelencoder.fit_transform(predictors[:, 3])
predictors[:, 5] = labelencoder.fit_transform(predictors[:, 5])
predictors[:, 6] = labelencoder.fit_transform(predictors[:, 6])
predictors[:, 8] = labelencoder.fit_transform(predictors[:, 8])
predictors[:, 9] = labelencoder.fit_transform(predictors[:, 9])
predictors[:, 11] = labelencoder.fit_transform(predictors[:, 11])
predictors[:, 13] = labelencoder.fit_transform(predictors[:, 13])
predictors[:, 14] = labelencoder.fit_transform(predictors[:, 14])
predictors[:, 16] = labelencoder.fit_transform(predictors[:, 16])
predictors[:, 18] = labelencoder.fit_transform(predictors[:, 18])
predictors[:, 19] = labelencoder.fit_transform(predictors[:, 19])

In [5]:
#  split between training e test (30%/70%)
X_training, X_test, y_training, y_test = train_test_split(predictors,
                                                                  vclass,
                                                                  test_size = 0.3,
                                                                  random_state = 1)

In [6]:
# create and training model predictions and hitrate 
svm = SVC()
svm.fit(X_training, y_training)

SVC()

In [7]:
#prevision
prevision = svm.predict(X_test)
prevision

array(['good', 'bad', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'bad', 'good', 'good',
       'bad', 'good', 'good', 'bad', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'bad', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good'], dtype=object)

In [8]:
hitrate = accuracy_score(y_test, prevision)
hitrate

0.7166666666666667

In [9]:
# Using  ExtraTreesClassifier to get the most important arguments 
forest = ExtraTreesClassifier()
forest.fit(X_training, y_training)
importances = forest.feature_importances_
importances

array([0.10443303, 0.08071906, 0.06759159, 0.05815213, 0.08370507,
       0.05452265, 0.05009138, 0.05387237, 0.04087679, 0.02943489,
       0.04796284, 0.0486211 , 0.07150188, 0.04120013, 0.03326117,
       0.03131731, 0.04342698, 0.02291909, 0.02981131, 0.00657924])

In [10]:
# creating a new database only with the most important attributes
X_training2 = X_training[:,[0,1,2,3]]
X_test2 = X_test[:,[0,1,2,3]]

In [11]:
# creating another model
svm2 = SVC()
svm2.fit(X_training2, y_training)
prevision2 = svm2.predict(X_test2)
hitrate = accuracy_score(y_test, prevision2)
hitrate

0.7233333333333334